---
# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/,http://localhost:8011/eureka/,http://localhost:8012/eureka/,http://localhost:8013/eureka/
server:
  port: 8030
  
info:
  component: Turbine

turbine:
  clusterNameExpression: new String("default")
  appConfig: sentence,subject,verb,article,adjective,noun

#turbine:
#  aggregator:
#    clusterConfig: SENTENCE,SUBJECT,VERB,ARTICLE,ADJECTIVE,NOUN
#  appConfig: sentence,subject,verb,article,adjective,noun

#turbine:
#  aggregator:
#    clusterConfig: AllServers
#  appConfig: sentence,subject,verb,article,adjective,noun
#  ConfigPropertyBasedDiscovery:
#    default:
#      instances: sentence,subject,verb,article,adjective,noun
#    AllServers:  
#      instances: sentence,subject,verb,article,adjective,noun

management:
  port: 8990  
