---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kennyk65/Microservices-With-Spring-Student-Files
          searchPaths: ConfigData
server:
  port: 8443
  ssl:
    key-store: classpath:mykeystore.jks
    key-store-password: secret
    key-password: secret  